#!/bin/bash

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
export PATH=$PATH

# Define
SRC="/usr/local/src"

# DNS
grep 202.106.0.20 /etc/resolv.conf >/dev/null 2>&1||echo 'nameserver 202.106.0.20' >> /etc/resolv.conf
grep 219.141.136.10 /etc/resolv.conf >/dev/null 2>&1||echo 'nameserver 114.114.114.114' >> /etc/resolv.conf
grep 114.114.114.114 /etc/resolv.conf >/dev/null 2>&1||echo 'nameserver 219.141.136.10' >> /etc/resolv.conf
grep 8.8.8.8 /etc/resolv.conf >/dev/null 2>&1||echo 'nameserver 8.8.8.8' >> /etc/resolv.conf
grep 4.4.4.4 /etc/resolv.conf >/dev/null 2>&1||echo 'nameserver 4.4.4.4' >> /etc/resolv.conf

# Distribution & Release
distribution=$(cat /etc/redhat-release|awk '{print $1}')
release=$(cat /etc/issue|grep release|awk '{print int($3)}')
[ "$release" -eq 5 ] && release=5.11
[ "$release" -eq 6 ] && release=6.6

# YUM & init
cd /etc/yum.repos.d/
curl http://mirrors.163.com/.help/CentOS${release}-Base-163.repo > CentOS${release}-Base-163.repo
yum -y update bash
yum -y install parted dmidecode
yum -y install man ntp ntpdate screen chkconfig
yum -y install vixie-cron crontabs ftp vsftpd httpd memcached subversoin createrepo
yum -y install wget lrzsz zip unzip tree vim mlocate dos2unix patch rsync sed
yum -y install gcc gcc-c++ autoconf automake make cmake
yum -y install tcpdump telnet sysstat lsof strace iptraf iotop ifstat sar
yum -y install rkhunter chkrootkit tripwire aide

# Tools
## iftop
wget http://www.ex-parrot.com/pdw/iftop/download/iftop-0.17.tar.gz -P $SRC/
tar --overwrite -zxvf $SRC/iftop-0.17.tar.gz -C $SRC/
cd $SRC/iftop-0.17
./configure
make && make install

# Env
grep MrUse ~/.bashrc||cat >> ~/.bashrc <<BASHRC
# @Start ~/.bashrc by MrUse
## Color
export red='\e[1;31m'
export redbg='\e[1;41m'
export blue='\e[1;34m'
export bluebg='\e[1;44m'
export green='\e[1;32m'
export greenbg='\e[1;42m'
export eol='\e[0m'

## Alias
alias wget="wget -c"
alias grep='grep -v grep|grep '
alias zip='zip -x *.DS_Store -x "*/\.*" -x "\.*"'
alias tar='tar --exclude=*.DS_Store --exclude=Thumbs.db '
# @end ~/.bashrc by MrUse
BASHRC

grep MrUse ~/.wgetrc||cat >> ~/.wgetrc <<WGETRC
# @start ~/.wgetrc Create by me@mruse.cn $(date +%F_%T)
Header=User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:37.0) Gecko/20100101 Firefox/37.0 Marked by MrUse
Header=Referer: https://www.baidu.com/
#http_proxy=""
#ftp_proxy=""
# @end ~/.wgetrc
WGETRC

grep MrUse ~/.curlrc||cat >> ~/.curlrc <<CURLRC
# @start ~/.curlrc Create by me@mruse.cn $(date +%F_%T)
User-Agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:37.0) Gecko/20100101 Firefox/37.0 Marked by MrUse"
Header="X-Forwarded-For: https://www.baidu.com/"
# @end ~/.curlrc
CURLRC

# @todo: nmon
# @todo: GoAccess
# @todo: bash
# @todo: ~/.vimrc  # http://www.jianshu.com/p/a0b452f8f720
